from pathlib import Path

import joblib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

# Default artifact location (gitignored; regenerated by train_intent.py).
DEFAULT_MODEL_PATH = Path(__file__).parent / "intent_classifier.joblib"


class IntentClassifier:
    """TF-IDF + LogisticRegression intent classifier with joblib persistence."""

    def __init__(self, model_path: str | Path | None = DEFAULT_MODEL_PATH):
        # Load the trained artifact once at construction
        self.pipeline: Pipeline | None = None
        if model_path is not None and Path(model_path).exists():
            self.pipeline = joblib.load(model_path)

    def train(self, data: list[tuple[str, str]]) -> None:
        # split (query, label) tuples, build the pipeline, fit.
        texts = [query for query, _ in data]
        labels = [label for _, label in data]
        self.pipeline = Pipeline([
            ("tfidf", TfidfVectorizer(ngram_range=(1, 2))),  # text → numbers
            ("clf", LogisticRegression(max_iter=1000)),       # → class
        ])
        self.pipeline.fit(texts, labels)

    def predict(self, query: str) -> tuple[str, float]:
        # predicted label + confidence = max class probability.
        if self.pipeline is None:
            raise RuntimeError("Classifier not trained/loaded — run train() or load an artifact")
        intent = self.pipeline.predict([query])[0]
        confidence = max(self.pipeline.predict_proba([query])[0])
        return intent, float(confidence)

    def save(self, model_path: str | Path = DEFAULT_MODEL_PATH) -> None:
        # persist the fitted pipeline
        if self.pipeline is None:
            raise RuntimeError("Nothing to save — train() first")
        joblib.dump(self.pipeline, model_path)
