# Intent-classifier training data
#
# - Labels are search / extract / summarize
# - Romanian queries grounded in this project's domain (facturi/contracte:
#   furnizor, client, CUI, TVA, total, IBAN, termen de plată…), matching the
#   sample_docs and the demo_prompt_cache.py question style.
# - A separate, DISJOINT TEST_DATA set is kept here too, so the train/test
#   split used by demo_intent_classifier.py is explicit

# query → label. Three intents (classes):
#   search     — locate / list / show documents
#   extract    — pull a specific structured field out of a document
#   summarize  — condense a document into key points
TRAINING_DATA: list[tuple[str, str]] = [
    # SEARCH — find / locate / list documents
    ("găsește facturile din martie", "search"),
    ("caută contractul cu TechPro", "search"),
    ("arată documentele din 2024", "search"),
    ("listează toate facturile emise", "search"),
    ("vreau să văd contractul de consultanță", "search"),
    ("unde este factura FV-2024-001", "search"),
    ("afișează facturile peste 10000 lei", "search"),
    ("caută documentele clientului Digital Services", "search"),
    ("găsește contractele de servicii", "search"),
    ("arată-mi facturile neplătite", "search"),
    ("deschide factura 002", "search"),
    ("vreau toate documentele cu TVA 19%", "search"),
    ("caută facturile furnizorului TechPro Solutions", "search"),
    ("listează contractele active", "search"),
    ("găsește documentele din sectorul 1", "search"),
    ("arată facturile scadente luna aceasta", "search"),
    ("unde găsesc antecontractul", "search"),
    ("caută după CUI RO12345678", "search"),
    ("vreau să găsesc toate facturile din 2024", "search"),
    ("afișează lista de facturi", "search"),
    ("selectează contractele semnate anul trecut", "search"),
    ("care sunt facturile emise către Digital Services", "search"),
    ("am nevoie de contractul de servicii", "search"),
    ("filtrează facturile după valoare", "search"),
    ("identifică documentele cu scadență depășită", "search"),
    ("accesează factura cu numărul FV-2024-002", "search"),
    ("dă-mi lista contractelor de consultanță", "search"),
    ("caută toate documentele clientului", "search"),
    ("arată facturile din trimestrul unu", "search"),
    ("găsește contractul semnat cu furnizorul", "search"),
    ("vreau facturile de peste 5000 de lei", "search"),
    ("listează documentele încărcate recent", "search"),
    ("unde sunt facturile din luna aprilie", "search"),
    ("caută factura cu totalul 18088", "search"),
    ("afișează contractele care expiră curând", "search"),
    ("găsește-mi toate antecontractele", "search"),
    ("arată documentele asociate cu CUI RO87654321", "search"),
    ("vreau să văd toate facturile fiscale", "search"),
    ("caută contractele cu valoare mare", "search"),
    ("listează facturile plătite", "search"),
    ("identifică contractul de consultanță din 2024", "search"),
    ("deschide documentul cu factura furnizorului", "search"),
    ("găsește facturile întocmite de Maria Ionescu", "search"),
    ("arată-mi documentele din București", "search"),
    ("caută facturile cu plată prin transfer bancar", "search"),
    ("vreau lista produselor comandate", "search"),
    ("afișează toate documentele din baza de date", "search"),
    ("găsește contractul după numărul de înregistrare", "search"),
    ("caută documentele scadente săptămâna aceasta", "search"),
    ("listează facturile ordonate după dată", "search"),

    # EXTRACT — pull a specific field out of a document (50)
    ("extrage totalul din factura 001", "extract"),
    ("scoate CUI-ul furnizorului", "extract"),
    ("care este valoarea TVA din factura FV-2024-001", "extract"),
    ("extrage datele clientului din contract", "extract"),
    ("ia IBAN-ul din factură", "extract"),
    ("cât este totalul de plată", "extract"),
    ("extrage termenul de plată din factură", "extract"),
    ("scoate numele produselor din factura 001", "extract"),
    ("parsează datele din PDF-ul atașat", "extract"),
    ("extrage modalitatea de plată", "extract"),
    ("care e numărul facturii", "extract"),
    ("dă-mi cantitatea de laptopuri din factură", "extract"),
    ("extrage subtotalul și TVA-ul", "extract"),
    ("scoate adresa furnizorului", "extract"),
    ("extrage data emiterii facturii", "extract"),
    ("care este prețul unitar al monitorului", "extract"),
    ("ia toate sumele din contract", "extract"),
    ("extrage numărul de înregistrare J40", "extract"),
    ("scoate numele persoanei care a întocmit factura", "extract"),
    ("extrage CUI-ul clientului din document", "extract"),
    ("cât TVA are factura FV-2024-001", "extract"),
    ("obține IBAN-ul furnizorului", "extract"),
    ("returnează totalul de plată al facturii 002", "extract"),
    ("spune-mi data scadentă a facturii", "extract"),
    ("citește numărul facturii din document", "extract"),
    ("extrage valoarea subtotalului", "extract"),
    ("care este cantitatea de monitoare comandate", "extract"),
    ("dă-mi denumirea produselor din factură", "extract"),
    ("scoate prețul unitar al laptopului", "extract"),
    ("extrage numele furnizorului din factură", "extract"),
    ("identifică valoarea totală a contractului", "extract"),
    ("ia adresa clientului din document", "extract"),
    ("extrage codul J40 al furnizorului", "extract"),
    ("cât costă tastatura din factură", "extract"),
    ("scoate data emiterii din factura 001", "extract"),
    ("care e modalitatea de plată din contract", "extract"),
    ("extrage toate valorile în RON", "extract"),
    ("dă-mi numărul de înregistrare al firmei", "extract"),
    ("obține numele clientului din factură", "extract"),
    ("extrage procentul de TVA aplicat", "extract"),
    ("scoate termenul de plată în zile", "extract"),
    ("care este IBAN-ul din factura 001", "extract"),
    ("extrage suma totală cu TVA inclus", "extract"),
    ("ia numele întocmitorului facturii", "extract"),
    ("spune-mi valoarea fără TVA", "extract"),
    ("extrage detaliile bancare din factură", "extract"),
    ("scoate orașul furnizorului", "extract"),
    ("care sunt produsele și cantitățile lor", "extract"),
    ("extrage numărul facturii și data", "extract"),
    ("dă-mi totalul produselor din factură", "extract"),

    # SUMMARIZE — condense a document into key points
    ("rezumă contractul de consultanță", "summarize"),
    ("fă-mi un sumar al facturii 001", "summarize"),
    ("sintetizează clauzele contractului", "summarize"),
    ("dă-mi un rezumat pe scurt al documentului", "summarize"),
    ("descrie pe scurt factura FV-2024-001", "summarize"),
    ("sumarizează contractul de servicii", "summarize"),
    ("rezumă-mi principalele puncte din contract", "summarize"),
    ("fă un rezumat al antecontractului", "summarize"),
    ("pe scurt, despre ce e factura asta", "summarize"),
    ("rezumă conținutul documentului", "summarize"),
    ("sintetizează termenii de plată", "summarize"),
    ("vreau un sumar al facturilor din martie", "summarize"),
    ("rezumă obligațiile părților din contract", "summarize"),
    ("fă-mi o sinteză a documentului", "summarize"),
    ("rezumă clauzele de reziliere", "summarize"),
    ("descrie pe scurt produsele facturate", "summarize"),
    ("sumarizează-mi contractul în câteva fraze", "summarize"),
    ("rezumă raportul lunar", "summarize"),
    ("dă-mi esența contractului", "summarize"),
    ("fă un overview al facturii", "summarize"),
    ("prezintă pe scurt contractul de consultanță", "summarize"),
    ("condensează informațiile din factură", "summarize"),
    ("explică pe scurt despre ce e documentul", "summarize"),
    ("care e esența contractului de servicii", "summarize"),
    ("în câteva cuvinte, ce conține factura", "summarize"),
    ("rezumă-mi documentul în trei fraze", "summarize"),
    ("fă o scurtă descriere a antecontractului", "summarize"),
    ("sintetizează produsele și sumele din factură", "summarize"),
    ("dă-mi un sumar al obligațiilor de plată", "summarize"),
    ("rezumă principalele clauze ale contractului", "summarize"),
    ("sumarizează conținutul facturii fiscale", "summarize"),
    ("prezintă-mi pe scurt termenii contractuali", "summarize"),
    ("fă un rezumat al detaliilor de plată", "summarize"),
    ("descrie succint factura FV-2024-001", "summarize"),
    ("rezumă-mi ce produse au fost facturate", "summarize"),
    ("dă-mi pe scurt informațiile despre furnizor", "summarize"),
    ("sintetizează raportul de activitate", "summarize"),
    ("rezumă documentul pentru o prezentare", "summarize"),
    ("fă-mi un sumar executiv al contractului", "summarize"),
    ("condensează clauzele importante", "summarize"),
    ("explică pe scurt obligațiile furnizorului", "summarize"),
    ("rezumă conținutul antecontractului ERA", "summarize"),
    ("care sunt punctele cheie ale documentului", "summarize"),
    ("sumarizează factura într-o frază", "summarize"),
    ("dă-mi un rezumat al valorii totale", "summarize"),
    ("prezintă pe scurt produsele și prețurile", "summarize"),
    ("fă o sinteză a termenilor de livrare", "summarize"),
    ("rezumă-mi pe scurt contractul semnat", "summarize"),
    ("descrie în linii mari documentul", "summarize"),
    ("fă un scurt rezumat al facturii 002", "summarize"),
]


TEST_DATA: list[tuple[str, str]] = [
    # search
    ("caută facturile emise în aprilie", "search"),
    ("arată contractul cu Digital Services", "search"),
    ("găsește documentele scadente", "search"),
    ("listează facturile cu TVA", "search"),
    ("unde e contractul de servicii", "search"),
    ("vreau să văd factura 002", "search"),
    ("afișează contractele din 2023", "search"),
    ("caută documentele furnizorului", "search"),
    ("găsește facturile recente", "search"),
    ("listează toate contractele", "search"),
    # extract
    ("extrage totalul de plată din factura 002", "extract"),
    ("care este CUI-ul clientului", "extract"),
    ("scoate termenul de plată din contract", "extract"),
    ("ia valoarea subtotalului", "extract"),
    ("extrage data scadentă", "extract"),
    ("dă-mi IBAN-ul furnizorului", "extract"),
    ("care e numărul de înregistrare J40", "extract"),
    ("extrage prețul tastaturii", "extract"),
    ("scoate numele clientului", "extract"),
    ("cât este TVA-ul total", "extract"),
    # summarize
    ("rezumă factura 002", "summarize"),
    ("fă-mi un sumar al contractului de servicii", "summarize"),
    ("sintetizează documentul pe scurt", "summarize"),
    ("descrie pe scurt antecontractul", "summarize"),
    ("dă-mi un rezumat al obligațiilor de plată", "summarize"),
    ("sumarizează clauzele principale", "summarize"),
    ("rezumă raportul de activitate", "summarize"),
    ("fă un overview al contractului", "summarize"),
    ("prezintă pe scurt factura", "summarize"),
    ("condensează termenii contractuali", "summarize"),
]

# Canonical label set (ordering used in reports).
LABELS: list[str] = ["search", "extract", "summarize"]
